version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: immer
    versions:
    - 8.0.1
    - 8.0.3
    - 9.0.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.5
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.15
    - 7.13.9
  - dependency-name: browserslist
    versions:
    - 4.16.1
  - dependency-name: husky
    versions:
    - 4.3.0
